set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(RISCV_TOOLCHAIN_PREFIX "riscv64-linux-gnu-" CACHE STRING "RISC-V GNU toolchain prefix")

set(CMAKE_C_COMPILER   "${RISCV_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${RISCV_TOOLCHAIN_PREFIX}g++")

set(RISCV_MARCH "rv64gcv" CACHE STRING "RISC-V ISA string")
set(RISCV_MABI  "lp64d" CACHE STRING "RISC-V ABI")

set(CMAKE_C_FLAGS_INIT   "-march=${RISCV_MARCH} -mabi=${RISCV_MABI}")
set(CMAKE_CXX_FLAGS_INIT "-march=${RISCV_MARCH} -mabi=${RISCV_MABI}")
