#!/usr/bin/env bash
set -euo pipefail

# Expected location:
#   <ara-root>/apps/rtx-rf-classify/Systems/ara_build.sh
#
# This script keeps the Git checkout intact and generates a small Ara app at:
#   <ara-root>/apps/rf_classify

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
ARA_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd -P)"
ARA_APPS_DIR="${ARA_ROOT}/apps"
COMMON_DIR="${ARA_APPS_DIR}/common"

APP="${APP:-rf_classify}"
SRC_DIR="${SRC_DIR:-${SCRIPT_DIR}/src}"
BIN_DIR="${BIN_DIR:-${SCRIPT_DIR}/scripts/binaries}"
APP_DIR="${ARA_APPS_DIR}/${APP}"
MDSPAN_INCLUDE_DIR="${MDSPAN_INCLUDE_DIR:-${SCRIPT_DIR}/../build/_deps/mdspan-src/include}"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

require_file() {
  [[ -f "$1" ]] || die "missing required file: $1"
}

require_dir() {
  [[ -d "$1" ]] || die "missing required directory: $1"
}

require_dir "${ARA_APPS_DIR}"
require_dir "${COMMON_DIR}"
require_dir "${SRC_DIR}"
require_dir "${SRC_DIR}/ExprSystem"
require_dir "${BIN_DIR}"
require_file "${SRC_DIR}/main.cpp"
require_file "${COMMON_DIR}/rfio.h"
require_file "${COMMON_DIR}/link.ld"

case "${APP}" in
  ""|common|bin|riscv-tests|rtx-rf-classify|.*|*/*)
    die "unsafe app name: ${APP}"
    ;;
esac

[[ "${APP_DIR}" != "${SCRIPT_DIR}" ]] || die "refusing to overwrite this checkout"
if [[ -d "${APP_DIR}/.git" ]]; then
  die "refusing to overwrite git checkout: ${APP_DIR}"
fi

require_dir "${MDSPAN_INCLUDE_DIR}/experimental"
require_dir "${MDSPAN_INCLUDE_DIR}/mdspan"

mapfile -t weight_bins < <(find "${BIN_DIR}" -maxdepth 1 -type f -name '*.bin' | sort)
[[ "${#weight_bins[@]}" -gt 0 ]] || die "no .bin weight files found in ${BIN_DIR}"

echo "Ara root:      ${ARA_ROOT}"
echo "Source:        ${SRC_DIR}"
echo "Generated app: ${APP_DIR}"
echo "App name:      ${APP}"

rm -rf "${APP_DIR}"
mkdir -p "${APP_DIR}/ExprSystem" "${APP_DIR}/weights"

cp "${SRC_DIR}/main.cpp" "${APP_DIR}/main.cpp"

find "${SRC_DIR}" -maxdepth 1 -type f -name '*.h' -print0 |
  while IFS= read -r -d '' header; do
    case "$(basename "${header}")" in
      network.h)
        ;;
      *)
        cp "${header}" "${APP_DIR}/"
        ;;
    esac
  done

cp "${SRC_DIR}/ExprSystem/"*.h "${APP_DIR}/ExprSystem/"
cp "${COMMON_DIR}/rfio.h" "${APP_DIR}/rfio.h"

if [[ -f "${SRC_DIR}/manual_blas.h" ]]; then
  cp "${SRC_DIR}/manual_blas.h" "${APP_DIR}/manual_blas.h"
  cp "${SRC_DIR}/manual_blas.h" "${APP_DIR}/blas_ops.h"
fi

cp -R "${MDSPAN_INCLUDE_DIR}/experimental" "${APP_DIR}/experimental"
cp -R "${MDSPAN_INCLUDE_DIR}/mdspan" "${APP_DIR}/mdspan"

for bin in "${weight_bins[@]}"; do
  cp "${bin}" "${APP_DIR}/weights/"
done

weights_s="${APP_DIR}/weights.S"
{
  echo '/* Generated by ara_build.sh. */'
  echo '.section .l2, "aw", @progbits'
  for bin in "${APP_DIR}/weights/"*.bin; do
    base="$(basename "${bin}" .bin)"
    abs="$(realpath "${bin}")"
    echo
    echo '.balign 32'
    echo ".global ${base}_start"
    echo ".global ${base}_end"
    echo ".global ${base}_size"
    echo "${base}_start:"
    echo "  .incbin \"${abs}\""
    echo "${base}_end:"
    echo ".set ${base}_size, ${base}_end - ${base}_start"
  done
} > "${weights_s}"

common_flags=(
  -I"${APP_DIR}"
  -I"${COMMON_DIR}"
  -O3
  -ffast-math
  -fno-common
  -fno-builtin-printf
  -ffunction-sections
  -fdata-sections
)

cxx_flags=(
  "\$(RISCV_FLAGS)"
  "${common_flags[@]}"
  -std=gnu++23
  -fno-exceptions
  -fno-rtti
  -fno-use-cxa-atexit
  -fno-threadsafe-statics
)

echo "Building ${APP}..."
make -B -C "${ARA_APPS_DIR}" "bin/${APP}" \
  "RISCV_CXXFLAGS=${cxx_flags[*]}"

echo
echo "Built: ${ARA_APPS_DIR}/bin/${APP}"
