/**
 * Bare-metal entry point for the classification MVP.
 *
 * Mirrors src/main.cpp but targets Ara / Verilator: no Berkeley sockets, no
 * iostream, no exceptions, no heap.  Input comes from baremetal_input.S
 * (the wire-format fixture baked by generate_baremetal_input.py) and output
 * is written through HTIF via printf-over-htif (BareIOStream).
 *
 * The build system is responsible for:
 *   - Defining BAREMETAL_USE_ARA_PRINTF so baremetal_stream.h pulls in Ara's
 *     printf.h instead of <cstdio>.
 *   - Compiling with -fno-exceptions and -DUSE_BLAS unset so streams.h takes
 *     the abort-on-failure path and blas_ops.h takes the scalar fallback.
 *   - Linking weights.S (for the model parameters) and baremetal_input.S
 *     (for the test fixture) alongside this TU.
 *
 * Tunables (override at compile time with -D):
 *   BM_INFERENCE_BUFFER_BYTES - size of the workspace handed to MemoryBuffer
 *                               for the persistent input/output tensors.
 */

#include <array>
#include <cstddef>
#include <cstdint>

#include "memorybuffer.h"
#include "baremetal_stream.h"
#include "inference.h"

#ifndef BM_INFERENCE_BUFFER_BYTES
#  define BM_INFERENCE_BUFFER_BYTES (( 3 * 128 + 128 * 32 ) * sizeof(float) + 256)
#endif

// ────────────────────────────────────────────────────────────────────────────
// Baked fixture symbols.  Provided by Systems/src/baremetal_input.S which
// uses .incbin to embed the file generated by generate_baremetal_input.py.
// ────────────────────────────────────────────────────────────────────────────
extern "C" const unsigned char baremetal_input_start[];
extern "C" const unsigned char baremetal_input_end[];

// ────────────────────────────────────────────────────────────────────────────
// Optional Ara runtime hooks.  Wrapped in BAREMETAL_USE_ARA_PRINTF so the
// same TU can be dry-built on the host (Step 7's BUILD_BAREMETAL target) for
// quick iteration without the cross toolchain.
// ────────────────────────────────────────────────────────────────────────────
#if defined(BAREMETAL_USE_ARA_PRINTF)
extern "C" {
#include "runtime.h"   // start_timer / stop_timer / get_timer
#include "printf.h"    // printf for HTIF
}
#  define BM_INFO(fmt, ...)   printf(fmt, ##__VA_ARGS__)
#  define BM_TIMER_START()    start_timer()
#  define BM_TIMER_STOP()     stop_timer()
#  define BM_TIMER_REPORT()   printf("[CYCLES] %ld\n", (long)get_timer())
#else
#  include <cstdio>
#  define BM_INFO(fmt, ...)   std::printf(fmt, ##__VA_ARGS__)
#  define BM_TIMER_START()    ((void)0)
#  define BM_TIMER_STOP()     ((void)0)
#  define BM_TIMER_REPORT()   std::printf("[CYCLES] (host build, no timer)\n")
#endif

// ────────────────────────────────────────────────────────────────────────────
// Persistent storage for the MemoryBuffer that backs the input / output
// f32Tensors.  Lives in .bss so we don't depend on a heap.  Kept aligned to
// 32 bytes to match the f32Tensor allocator's alignment requirement.
// ────────────────────────────────────────────────────────────────────────────
alignas(32) static std::array<std::byte, BM_INFERENCE_BUFFER_BYTES> g_io_storage{};

int main() {
    BM_INFO("[boot] classify_mvp starting; fixture=%zu bytes\n",
            static_cast<std::size_t>(baremetal_input_end - baremetal_input_start));

    MemoryBuffer io_buf{ std::span<std::byte>{ g_io_storage.data(), g_io_storage.size() } };
    auto io_alloc = io_buf.get_allocator<float, 32>();

    f32Tensor<3, 128>  input(io_alloc);
    f32Tensor<128, 32> output(io_alloc);

    BareIOStream<> io(baremetal_input_start, baremetal_input_end);

    BM_TIMER_START();
    serve_inference(io, input, output);
    BM_TIMER_STOP();
    BM_TIMER_REPORT();

    BM_INFO("[done] classify_mvp finished\n");
    return 0;
}
